### ISSUE TITLE
启动nb2报错：KeyError: 'aidraw'

### ISSUE THREAD

**Issue by Umamusume-Agnes-Digital** [CMHopeSunshine/nonebot-plugin-learning-chat#1]
```
01-04 22:55:18 [ERROR] uvicorn | Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/tortoise/connection.py", line 113, in get
    return storage[conn_alias]
KeyError: 'aidraw'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/tortoise/connection.py", line 76, in _get_db_info
    return self.db_config[conn_alias]
KeyError: 'aidraw'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 530, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 612, in startup
    await handler()
  File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_learning_chat/models.py", line 131, in startup
    await Tortoise.init(db_url=f'sqlite://{DATABASE_PATH}', modules={'models': [__name__]})
  File "/usr/local/lib/python3.9/dist-packages/tortoise/__init__.py", line 574, in init
    cls._init_apps(apps_config)
  File "/usr/local/lib/python3.9/dist-packages/tortoise/__init__.py", line 417, in _init_apps
    cls._build_initial_querysets()
  File "/usr/local/lib/python3.9/dist-packages/tortoise/__init__.py", line 440, in _build_initial_querysets
    model._meta.finalise_model()
  File "/usr/local/lib/python3.9/dist-packages/tortoise/models.py", line 308, in finalise_model
    self._generate_filters()
  File "/usr/local/lib/python3.9/dist-packages/tortoise/models.py", line 476, in _generate_filters
    get_overridden_filter_func = self.db.executor_class.get_overridden_filter_func
  File "/usr/local/lib/python3.9/dist-packages/tortoise/models.py", line 288, in db
    return connections.get(self.default_connection)
  File "/usr/local/lib/python3.9/dist-packages/tortoise/connection.py", line 115, in get
    connection: BaseDBAsyncClient = self._create_connection(conn_alias)
  File "/usr/local/lib/python3.9/dist-packages/tortoise/connection.py", line 90, in _create_connection
    db_info = self._get_db_info(conn_alias)
  File "/usr/local/lib/python3.9/dist-packages/tortoise/connection.py", line 78, in _get_db_info
    raise ConfigurationError(
tortoise.exceptions.ConfigurationError: Unable to get db settings for alias 'aidraw'. Please check if the config dict contains this alias and try again

01-04 22:55:18 [ERROR] uvicorn | Application startup failed. Exiting.
```

**Comment by CMHopeSunshine** [comment]
已在`0.1.1`版本修复 7472e1a2e0c33e75fb74afa50287f1dd78442ec9 ，`pip install nonebot-plugin-learning-chat --upgrade`进行更新即可，如果用的是镜像源的话，要等一会，等待镜像源同步。
