### ISSUE TITLE
[ERROR] apscheduler | Job "speak_up (trigger: interval[0:01:00], next run at: 2023-01-13 17:53:27 CST)" raised an exception Traceback (most recent call last)

### ISSUE THREAD

**Issue by Zwc84** [CMHopeSunshine/nonebot-plugin-learning-chat#16]
您好，首先我并不太清楚这到底是代码的错误还是我个人配置的错误
目前已知Nonebot-plugin-reboot，nonebot_plugin_apscheduler，以及大佬的这个插件。这三者产生了非常微妙的关系
表现大概是出现下面这个报错的时候。指令，无法使用
如果是我个人原因的话就麻烦大佬指一条明路了，谢谢·

01-13 17:52:27 [ERROR] apscheduler | Job "speak_up (trigger: interval[0:01:00], next run at: 2023-01-13 17:53:27 CST)" raised an exception
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ZWC13\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ZWC13\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\ZWC13\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\ZWC13\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ZWC13\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_reboot\reloader.py", line 27, in _run
    _nb_run(*args, **kwargs)
  File "C:\Users\ZWC13\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\ZWC13\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\ZWC13\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\ZWC13\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\ZWC13\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ZWC13\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\ZWC13\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\ZWC13\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\ZWC13\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
  File "C:\Users\ZWC13\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\ZWC13\AppData\Local\Programs\Python\Python310\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "C:\Users\ZWC13\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_learning_chat\__init__.py", line 72, in speak_up
    if not (speak := await LearningChat.speak(int(bot.self_id))):
  File "C:\Users\ZWC13\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_learning_chat\handler.py", line 390, in speak
    if cur_time - last_reply.time < config.speak_min_interval:
AttributeError: 'NoneType' object has no attribute 'time'

[错误]apscheduler |作业“speak_up（触发器：interval[0:01:00]，下次运行时间：2023-01-13 17:53:27 CST）”引发异常
AttributeError:“NoneType”对象没有属性“time”
ps:(我个人感觉的话很有可能是我自己的错误，如果真的是的话就麻烦各位大佬下手轻一点儿qwq)
(在学了，在学了，看了一个下午了。最终还是没有解决掉。果然我还是一个fw23333)

**Comment by CMHopeSunshine** [comment]
应该是我代码的问题，忘记处理None的情况了，待会我看看

**Comment by Zwc84** [comment]
好的，麻烦大佬了

**Comment by CMHopeSunshine** [comment]
修复了，等发版之后更新到最新版试试
