### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by NealScx** [CMHopeSunshine/nonebot-plugin-learning-chat#19]
01-18 21:42:33 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_repeater)
01-18 21:42:33 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_repeater) running complete
01-18 21:42:33 [ERROR] nonebot | Rule check failed for Matcher(type='message', module=nonebot_plugin_learning_chat).
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/tortoise/backends/sqlite/client.py", line 34, in translate_exceptions_
    return await func(self, query, *args)
  File "/usr/local/lib/python3.9/dist-packages/tortoise/backends/sqlite/client.py", line 117, in execute_insert
    return (await connection.execute_insert(query, values))[0]
  File "/usr/local/lib/python3.9/dist-packages/aiosqlite/core.py", line 194, in execute_insert
    return await self._execute(self._execute_insert, sql, parameters)
  File "/usr/local/lib/python3.9/dist-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/usr/local/lib/python3.9/dist-packages/aiosqlite/core.py", line 102, in run
    result = function()
  File "/usr/local/lib/python3.9/dist-packages/aiosqlite/core.py", line 74, in _execute_insert
    cursor = self._conn.execute(sql, parameters)
sqlite3.OperationalError: no such table: message

**Comment by CMHopeSunshine** [comment]
请更新到最新版

**Comment by CMHopeSunshine** [comment]
重启一下试试？可能是别的使用tortoise-orm的插件把本插件的数据库连接给关闭了

**Comment by TsukasaYahane** [comment]
![image](https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat/assets/121178437/db27506a-c9b4-48df-b615-21496fb8dd3a)
0.22版本也是这个问题，初步推断是和[nonebot-plugin-chatgpt-plus](https://github.com/AkashiCoin/nonebot-plugin-chatgpt-plus)这个插件产生冲突。发生冲突后在webUI提示
![image](https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat/assets/121178437/66cebd29-827e-4fe8-b602-b0ab0e46d814)

**Comment by CMHopeSunshine** [comment]
> ![image](https://user-images.githubusercontent.com/121178437/238150436-db27506a-c9b4-48df-b615-21496fb8dd3a.png) 0.22版本也是这个问题，初步推断是和[nonebot-plugin-chatgpt-plus](https://github.com/AkashiCoin/nonebot-plugin-chatgpt-plus)这个插件产生冲突。发生冲突后在webUI提示 ![image](https://user-images.githubusercontent.com/121178437/238150532-66cebd29-827e-4fe8-b602-b0ab0e46d814.png)

看了下这个插件没有用数据库，应该无关，能发一下`nonebot2`和`fastapi`版本号吗，(进入虚拟环境后)`pip show nonebot2`和`pip show fastapi`

**Comment by TsukasaYahane** [comment]
![image](https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat/assets/121178437/8b985b41-2c5f-48d1-8669-84810ba14b21)

**Comment by CMHopeSunshine** [comment]
版本没问题，应该是插件冲突了，tortoise-orm迟迟不发新版，没办法

**Comment by wlingzhenyu** [comment]
so,真的没办法解决了吗，我的也是会发生，重启就断，多重启几次又连上了，属实太影响了

**Comment by CMHopeSunshine** [comment]
后面会考虑一下把tortoise-orm换成sqlalchemy来解决数据库连接问题，不过不确定已学的数据能否无缝切换。
