### ISSUE TITLE
运行后报错

### ISSUE THREAD

**Issue by decatri** [CMHopeSunshine/nonebot-plugin-learning-chat#22]
02-06 16:36:08 [ERROR] apscheduler | Job "dy_sched (trigger: date[2023-02-06 16:36:08 CST], next run at: 2023-02-06 16:36:08 CST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\click\core.py", line 1130, in __call__
    return self. Main(*args, **kwargs)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\click\core.py", line 1055, in main
    rv = self. Invoke(ctx)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\haruka_bot\plugins\pusher\dynamic_pusher.py", line 34, in dy_sched
    await grpc_get_user_dynamics(uid, timeout=10, proxy=config.haruka_proxy)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\bilireq\grpc\utils\__init__.py", line 48, in wrapper
    result = await func(
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\bilireq\grpc\dynamic\__init__.py", line 20, in grpc_get_user_dynamics
    return await stub.DynSpace(req, **kwargs)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\grpc\aio\_call.py", line 290, in __await__
    raise _create_rpc_error(self._cython_call._initial_metadata,
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "DNS resolution failed for grpc.biliapi.net: UNAVAILABLE: WSA Error"
        debug_error_string = "UNKNOWN:DNS resolution failed for grpc.biliapi.net: UNAVAILABLE: WSA Error {grpc_status:14, created_time:"2023-02-06T08:36:08.3537447+00:00"}"
>
02-06 16:36:08 [ERROR] apscheduler | Job "dy_sched (trigger: date[2023-02-06 16:36:08 CST], next run at: 2023-02-06 16:36:08 CST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\haruka_bot\plugins\pusher\dynamic_pusher.py", line 34, in dy_sched
    await grpc_get_user_dynamics(uid, timeout=10, proxy=config.haruka_proxy)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\bilireq\grpc\utils\__init__.py", line 48, in wrapper
    result = await func(
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\bilireq\grpc\dynamic\__init__.py", line 20, in grpc_get_user_dynamics
    return await stub.DynSpace(req, **kwargs)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\grpc\aio\_call.py", line 290, in __await__
    raise _create_rpc_error(self._cython_call._initial_metadata,
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "DNS resolution failed for grpc.biliapi.net: UNAVAILABLE: WSA Error"
        debug_error_string = "UNKNOWN:DNS resolution failed for grpc.biliapi.net: UNAVAILABLE: WSA Error {created_time:"2023-02-06T08:36:08.4676504+00:00", grpc_status:14}"
>
02-06 16:36:08 [ERROR] apscheduler | Job "dy_sched (trigger: date[2023-02-06 16:36:08 CST], next run at: 2023-02-06 16:36:08 CST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\haruka_bot\plugins\pusher\dynamic_pusher.py", line 34, in dy_sched
    await grpc_get_user_dynamics(uid, timeout=10, proxy=config.haruka_proxy)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\bilireq\grpc\utils\__init__.py", line 48, in wrapper
    result = await func(
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\bilireq\grpc\dynamic\__init__.py", line 20, in grpc_get_user_dynamics
    return await stub.DynSpace(req, **kwargs)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\grpc\aio\_call.py", line 290, in __await__
    raise _create_rpc_error(self._cython_call._initial_metadata,
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "DNS resolution failed for grpc.biliapi.net: UNAVAILABLE: WSA Error"
        debug_error_string = "UNKNOWN:DNS resolution failed for grpc.biliapi.net: UNAVAILABLE: WSA Error {created_time:"2023-02-06T08:36:08.5741266+00:00", grpc_status:14}"
>
02-06 16:36:08 [ERROR] apscheduler | Job "dy_sched (trigger: date[2023-02-06 16:36:08 CST], next run at: 2023-02-06 16:36:08 CST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\46885\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\haruka_bot\plugins\pusher\dynamic_pusher.py", line 34, in dy_sched
    await grpc_get_user_dynamics(uid, timeout=10, proxy=config.haruka_proxy)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\bilireq\grpc\utils\__init__.py", line 48, in wrapper
    result = await func(
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\bilireq\grpc\dynamic\__init__.py", line 20, in grpc_get_user_dynamics
    return await stub.DynSpace(req, **kwargs)
  File "F:\nonebot2-oneclick-win-main\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-nG8oin8_-py3.10\lib\site-packages\grpc\aio\_call.py", line 290, in __await__
    raise _create_rpc_error(self._cython_call._initial_metadata,
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "DNS resolution failed for grpc.biliapi.net: UNAVAILABLE: WSA Error"
        debug_error_string = "UNKNOWN:DNS resolution failed for grpc.biliapi.net: UNAVAILABLE: WSA Error {grpc_status:14, created_time:"2023-02-06T08:36:08.7045436+00:00"}"
不知道是我这边插件冲突了还是怎么回事。望作者解答谢谢。

**Comment by decatri** [comment]
好的，谢谢
&nbsp;


时空旅行者
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月6日(星期一) 下午4:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CMHopeSunshine/nonebot-plugin-learning-chat] 运行后报错 (Issue #22)






非本插件问题，看似网络解析失败

—
直接回复此邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.
