### ISSUE TITLE
使用这个插件会触发py插件启动报错，插件所有的依赖都装了但是最后py插件全部加载完全部插件后报这个错误

### ISSUE THREAD

**Issue by lintonxue00** [CMHopeSunshine/nonebot-plugin-learning-chat#28]
Traceback (most recent call last):
File "/root/Yunzai-Bot/plugins/py-plugin/main.py", line 17, in
yunzai_nonebot.run()
File "/root/Yunzai-Bot/plugins/py-plugin/yunzai_nonebot/init.py", line 31, in run
nonebot.run(*args, **kwargs)
File "/root/.cache/pypoetry/virtualenvs/py-plugin-8_cve6GP-py3.9/lib/python3.9/site-packages/nonebot/init.py", line 273, in run
get_driver().run(*args, **kwargs)
File "/root/Yunzai-Bot/plugins/py-plugin/yunzai_nonebot/hijack/driver.py", line 42, in run
loop.run_until_complete(self.serve())
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
return future.result()
File "/root/Yunzai-Bot/plugins/py-plugin/yunzai_nonebot/hijack/driver.py", line 61, in serve
await self.startup()
File "/root/Yunzai-Bot/plugins/py-plugin/yunzai_nonebot/hijack/driver.py", line 76, in startup
await handler()
File "/root/Yunzai-Bot/plugins/py-plugin/plugins/nonebot-plugin-learning-chat/nonebot_plugin_learning_chat/web_api.py", line 61, in init_web
app: FastAPI = get_app()
File "/root/.cache/pypoetry/virtualenvs/py-plugin-8_cve6GP-py3.9/lib/python3.9/site-packages/nonebot/init.py", line 99, in get_app
assert isinstance(
AssertionError: app object is only available for reverse driver

**Comment by CMHopeSunshine** [comment]
py插件的nonebot是魔改的非完整版，请向py插件反馈
