### ISSUE TITLE
装了个别的插件之后报错

### ISSUE THREAD

**Issue by homeworkkun** [CMHopeSunshine/nonebot-plugin-learning-chat#30]
之前有些插件也会这样，卸载重装就好了，所以没怎么在意
但是这回卸载那个插件之后不管怎么重装都还是会报错QAQ
04-10 21:28:01 [ERROR] nonebot | Failed to import "nonebot_plugin_learning_chat"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "D:\QQBot\.venv\Lib\site-packages\nonebot\plugin\load.py", line 125, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "D:\QQBot\.venv\Lib\site-packages\nonebot\plugin\load.py", line 62, in load_all_plugins
    return manager.load_all_plugins()
  File "D:\QQBot\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 175, in load_all_plugins
    return set(
  File "D:\QQBot\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "D:\QQBot\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\homew\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\QQBot\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\QQBot\.venv\Lib\site-packages\nonebot_plugin_learning_chat\__init__.py", line 11, in <module>
    from .handler import LearningChat
  File "D:\QQBot\.venv\Lib\site-packages\nonebot_plugin_learning_chat\handler.py", line 17, in <module>
    from .models import ChatBlackList, ChatContext, ChatAnswer, ChatMessage
  File "D:\QQBot\.venv\Lib\site-packages\nonebot_plugin_learning_chat\models.py", line 17, in <module>
    from tortoise.models import Model
  File "D:\QQBot\.venv\Lib\site-packages\tortoise\models.py", line 25, in <module>
    from tortoise import connections
ImportError: cannot import name 'connections' from 'tortoise' (D:\QQBot\.venv\Lib\site-packages\tortoise\__init__.py)

**Comment by homeworkkun** [comment]
之前这套插件之间都没问题的，但是装了nonebot-plugin-blive-danmaku之后就出现了七八个插件报错，我把它删了重装一次其他插件之后就是一直提示Failed to import "nonebot_plugin_learning_chat"，整不明白（

**Comment by CMHopeSunshine** [comment]
把报错的库卸载重装一边
