### ISSUE TITLE
访问网页管理界面报错

### ISSUE THREAD

**Issue by hanasome** [CMHopeSunshine/nonebot-plugin-learning-chat#32]
05-10 12:16:40 [INFO] uvicorn | 20.27.129.30:0 - "GET /learning_chat/api/get_group_list HTTP/1.1" 500
05-10 12:16:40 [ERROR] uvicorn | Exception in ASGI application

Traceback (most recent call last):
  File "<string>", line 23, in <module>
  File "/home/ubuntu/mbot/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "/home/ubuntu/mbot/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 198, in run
    uvicorn.run(
  File "/home/ubuntu/mbot/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/ubuntu/mbot/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/home/ubuntu/mbot/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/ubuntu/mbot/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/ubuntu/mbot/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ubuntu/mbot/.venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ubuntu/mbot/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/ubuntu/mbot/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/ubuntu/mbot/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/ubuntu/mbot/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/ubuntu/mbot/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/ubuntu/mbot/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/ubuntu/mbot/.venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/ubuntu/mbot/.venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/ubuntu/mbot/.venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/ubuntu/mbot/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/home/ubuntu/mbot/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/ubuntu/mbot/.venv/lib/python3.10/site-packages/nonebot_plugin_learning_chat/web_api.py", line 85, in get_group_list_api
    group_list = [{'label': f'{group["group_name"]}({group["group_id"]})', 'value': group['group_id']} for group
TypeError: 'NoneType' object is not iterable
05-10 12:16:42 [ERROR] apscheduler | Job "speak_up (trigger: interval[0:03:00], next run at: 2023-05-10 20:19:42 CST)" raised an exception
Traceback (most recent call last):
  File "<string>", line 23, in <module>
  File "/home/ubuntu/mbot/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "/home/ubuntu/mbot/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 198, in run
    uvicorn.run(
  File "/home/ubuntu/mbot/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/ubuntu/mbot/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/home/ubuntu/mbot/.venv/lib/python3.10/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/home/ubuntu/mbot/.venv/lib/python3.10/site-packages/nonebot_plugin_learning_chat/__init__.py", line 72, in speak_up
    if not (speak := await LearningChat.speak(int(bot.self_id))):
ValueError: invalid literal for int() with base 10: 'console'

**Comment by CMHopeSunshine** [comment]
这是什么协议端啊，怎么qq号是叫`console`的。
本插件只支持qq
