### ISSUE TITLE
WEB UI接口报错："Internal Server Error"

### ISSUE THREAD

**Issue by Nenot233** [CMHopeSunshine/nonebot-plugin-learning-chat#4]
01-07 11:12:16 [ERROR] nonebot | Rule check failed for Matcher(type='message', module=extensive_plugin.nonebot_plugin_learning_chat).
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\backends\sqlite\client.py", line 34, in translate_exceptions_
    return await func(self, query, *args)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\backends\sqlite\client.py", line 141, in execute_query
    rows = await connection.execute_fetchall(query, values)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\aiosqlite\core.py", line 203, in execute_fetchall
    return await self._execute(self._execute_fetchall, sql, parameters)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\aiosqlite\core.py", line 129, in _execute
    return await future
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\aiosqlite\core.py", line 102, in run
    result = function()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\aiosqlite\core.py", line 81, in _execute_fetchall
    cursor = self._conn.execute(sql, parameters)
sqlite3.OperationalError: no such table: blacklist

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\BOT\zhenxun_bot\bot.py", line 22, in <module>
    nonebot.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
 File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\message.py", line 131, in _check_matcher
    ) or not await Matcher.check_rule(bot, event, state, stack, dependency_cache):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\internal\matcher.py", line 293, in check_rule
    return event_type == (cls.type or event_type) and await cls.rule(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\internal\rule.py", line 73, in __call__
    results = await asyncio.gather(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\BOT\zhenxun_bot\extensive_plugin\nonebot_plugin_learning_chat\__init__.py", line 38, in ChatRule
    if answers := await LearningChat(event).answer():
  File "D:\BOT\zhenxun_bot\extensive_plugin\nonebot_plugin_learning_chat\handler.py", line 145, in answer
    result = await self._learn()
  File "D:\BOT\zhenxun_bot\extensive_plugin\nonebot_plugin_learning_chat\handler.py", line 96, in _learn
    elif not await self._check_allow(self.data):
  File "D:\BOT\zhenxun_bot\extensive_plugin\nonebot_plugin_learning_chat\handler.py", line 495, in _check_allow
    if ban_word := await ChatBlackList.filter(keywords=message.keywords).first():
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\queryset.py", line 1006, in _execute
    instance_list = await self._db.executor_class(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\backends\base\executor.py", line 130, in execute_select
    _, raw_results = await self.db.execute_query(query.get_sql())
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\backends\sqlite\client.py", line 36, in translate_exceptions_
    raise OperationalError(exc)
tortoise.exceptions.OperationalError: no such table: blacklist

真寻NB版本：RC2
WIN10本地部署
偶尔型的接不上数据库是咋回事呢

**Comment by CMHopeSunshine** [comment]
更新到最新版试试，`pip install nonebot-plugin-learning-chat --upgrade`

**Comment by Nenot233** [comment]
更新到最新也是接口报错："Internal Server Error"

**Comment by CMHopeSunshine** [comment]
Internal Server Error的报错日志贴一下

**Comment by Nenot233** [comment]
是log文件吗？
WEB UI就显示这个
![image](https://user-images.githubusercontent.com/108965579/211129350-6445d06d-0d9a-46b6-bfdf-40175a61b1e8.png)
[新建文本文档 (4).txt](https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat/files/10365441/4.txt)

**Comment by CMHopeSunshine** [comment]
未知原因导致数据库连不上，可能是其他插件使用了相同数据库导致冲突。确认一下本插件版本是否为0.1.1，检查在bot目录是否有data/learning_chat/learning_chat.db文件。

**Comment by Nenot233** [comment]
![image](https://user-images.githubusercontent.com/108965579/211129640-63883c44-9b89-4581-9233-e18fa4480a5b.png)
learning_chat.db是有这个文件

**Comment by Nenot233** [comment]
![image](https://user-images.githubusercontent.com/108965579/211129916-be99b84a-b5aa-4988-a1ba-a0a94ed1aaac.png)
似乎是缺少这两个文件（莫名其妙就缺少了）

**Comment by CMHopeSunshine** [comment]
这两个是数据库连接的临时文件，重启一下就有了，现在能连上了吗

**Comment by Nenot233** [comment]
我把learning_chat.db文件删除后重新加载一个才能正常连接上，学习数据已经没了
删除之前一直重启也没有这两个文件

**Comment by Nenot233** [comment]
01-10 13:35:33 [ERROR] apscheduler | Job "speak_up (trigger: interval[0:01:00], next run at: 2023-01-10 13:36:33 CST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\backends\sqlite\client.py", line 34, in translate_exceptions_
    return await func(self, query, *args)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\backends\sqlite\client.py", line 141, in execute_query
    rows = await connection.execute_fetchall(query, values)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\aiosqlite\core.py", line 203, in execute_fetchall
    return await self._execute(self._execute_fetchall, sql, parameters)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\aiosqlite\core.py", line 129, in _execute
    return await future
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\aiosqlite\core.py", line 102, in run
    result = function()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\aiosqlite\core.py", line 81, in _execute_fetchall
    cursor = self._conn.execute(sql, parameters)
sqlite3.OperationalError: no such table: message

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\BOT\zhenxun_bot\bot.py", line 22, in <module>
    nonebot.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "D:\BOT\zhenxun_bot\extensive_plugin\nonebot_plugin_learning_chat\__init__.py", line 80, in speak_up
    if not (speak := await LearningChat.speak(int(bot.self_id))):
  File "D:\BOT\zhenxun_bot\extensive_plugin\nonebot_plugin_learning_chat\handler.py", line 347, in speak
    groups = await ChatMessage.filter(time__gte=today_time).annotate(count=Count('id')).group_by('group_id'). \
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\queryset.py", line 1495, in _execute
    _, result = await self._db.execute_query(str(self.query))
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\tortoise\backends\sqlite\client.py", line 36, in translate_exceptions_
    raise OperationalError(exc)
tortoise.exceptions.OperationalError: no such table: message

**Comment by Nenot233** [comment]
似乎找到报错了

**Comment by Nenot233** [comment]
更新至0.1.3还是会这样，无法读取数据库

**Comment by CMHopeSunshine** [comment]
是否还安装了其他使用tortoise-orm的插件，能贴一下models.py这个文件内容吗

**Comment by Nenot233** [comment]
[models.zip](https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat/files/10380624/models.zip)
以及依赖
absl-py                    1.2.0
addict                     2.4.0
aiocache                   0.11.1
aiodns                     3.0.0
aiofiles                   0.8.0
aiohttp                    3.7.4.post0
aiosignal                  1.2.0
aiosqlite                  0.17.0
amis-python                1.0.6
anyio                      3.6.2
appdirs                    1.4.4
APScheduler                3.9.1
arrow                      1.2.3
asgiref                    3.5.2
async-generator            1.10
async-timeout              3.0.1
asyncpg                    0.26.0
attrs                      22.1.0
audioread                  2.1.9
baike                      1.5.0
basicsr                    1.4.1
bbcode                     1.1.0
beautifulsoup4             4.9.3
bilireq                    0.2.3.post0
black                      22.10.0
Brotli                     1.0.9
CacheControl               0.12.11
cachetools                 5.2.0
cachy                      0.3.0
cchardet                   2.1.7
certifi                    2022.12.7
cffi                       1.15.1
chardet                    4.0.0
charset-normalizer         2.0.12
cleo                       1.0.0a5
click                      8.1.3
cn2an                      0.5.17
colorama                   0.4.6
commonmark                 0.9.1
contourpy                  1.0.5
crashtest                  0.3.1
cssselect                  1.1.0
cycler                     0.11.0
Cython                     0.29.28
dateparser                 1.1.1
DateTime                   4.7
decorator                  5.1.1
deep-translator            1.9.0
dill                       0.3.5.1
diskcache                  5.4.0
distlib                    0.3.6
dulwich                    0.20.46
ecdsa                      0.18.0
emoji                      1.7.0
exceptiongroup             1.0.0rc9
facexlib                   0.2.4
fastapi                    0.80.0
feedparser                 6.0.10
filelock                   3.8.0
filterpy                   1.4.5
fonttools                  4.37.4
frozenlist                 1.3.1
future                     0.18.2
fuzzywuzzy                 0.18.0
gensim                     4.2.0
gfpgan                     1.3.4
gino                       1.0.1
gitdb                      4.0.9
GitPython                  3.1.27
google-auth                2.10.0
google-auth-oauthlib       0.4.6
greenlet                   1.1.3
grpcio                     1.49.1
h11                        0.12.0
h2                         4.1.0
hpack                      4.0.0
html5lib                   1.1
httpcore                   0.14.7
httptools                  0.5.0
httpx                      0.22.0
hyperframe                 6.0.1
idna                       3.4
ImageHash                  4.3.1
imageio                    2.21.0
importlib-metadata         5.2.0
inflect                    5.6.2
iniconfig                  1.1.1
init                       0.1.0
install                    1.3.5
iso8601                    1.1.0
jaraco.classes             3.2.3
jieba                      0.42.1
jieba-fast                 0.53
Jinja2                     3.1.2
jiojio                     1.2.2
jionlp                     1.4.18
joblib                     1.1.0
jsonschema                 4.16.0
keyring                    23.9.3
kiwisolver                 1.4.4
langid                     1.1.6
librosa                    0.9.2
llvmlite                   0.36.0
lmdb                       1.3.0
lockfile                   0.12.2
loguru                     0.6.0
lxml                       4.6.5
magneturi                  1.3
Markdown                   3.4.1
MarkupSafe                 2.1.1
matplotlib                 3.6.0
mockingbirdforuse          0.2.3
more-itertools             9.0.0
msgpack                    1.0.4
multidict                  6.0.3
multiprocess               0.70.13
mypy-extensions            0.4.3
netifaces                  0.10.6
networkx                   2.8.5
nonebot-adapter-onebot     2.1.5
nonebot-plugin-apscheduler 0.2.0
nonebot-plugin-guild-patch 0.2.1
nonebot-plugin-htmlrender  0.2.0.1
nonebot-plugin-imageutils  0.1.7
nonebot-plugin-morning     0.2.2
nonebot-plugin-picsearcher 0.1.8
nonebot-plugin-txt2img     0.1.4
nonebot2                   2.0.0rc2
numba                      0.53.0
numpy                      1.24.0
oauthlib                   3.2.0
opencv-python              4.6.0.66
opencv-python-headless     4.6.0.66
outcome                    1.2.0
packaging                  22.0
pandas                     1.4.4
pathos                     0.2.8
pathspec                   0.10.1
pdfminer3k                 1.3.4
peewee                     3.15.3
pexpect                    4.8.0
picimagesearch             3.7.2
pikpakapi                  0.0.7
Pillow                     9.2.0
pip                        22.3.1
pkginfo                    1.8.3
platformdirs               2.5.2
playwright                 1.27.0
pluggy                     1.0.0
ply                        3.11
poetry                     1.2.2
poetry-core                1.3.2
poetry-plugin-export       1.1.2
pooch                      1.6.0
pox                        0.3.1
ppft                       1.7.6.5
prettytable                3.2.0
proces                     0.1.2
protobuf                   4.21.7
psutil                     5.9.2
ptyprocess                 0.7.0
pyasn1                     0.4.8
pyasn1-modules             0.2.8
pycares                    4.2.1
pycparser                  2.21
pydantic                   1.10.2
pydub                      0.25.1
pyee                       8.1.0
Pygments                   2.13.0
pygtrie                    2.5.0
pylev                      1.4.0
pymdown-extensions         9.7
pyparsing                  3.0.9
pypika-tortoise            0.1.6
pypinyin                   0.46.0
pyppeteer                  1.0.2
pyquery                    1.4.3
pyrsistent                 0.18.1
PySocks                    1.7.1
pytest                     7.2.0
pytest-base-url            2.0.0
pytest-playwright          0.3.0
python-dateutil            2.8.2
python-dotenv              0.21.0
python-jose                3.3.0
python-markdown-math       0.8
python-multipart           0.0.5
python-qbittorrent         0.4.3
python-slugify             6.1.2
pytz                       2022.4
pytz-deprecation-shim      0.1.0.post0
PyWavelets                 1.4.1
pywin32-ctypes             0.2.0
PyYAML                     5.4.1
qbittorrent                0.1.6
realesrgan                 0.2.5.0
regex                      2022.3.2
requests                   2.27.1
requests-oauthlib          1.3.1
requests-toolbelt          0.9.1
resampy                    0.3.1
retrying                   1.3.3
rfc3986                    1.5.0
rich                       12.6.0
rsa                        4.9
ruamel.yaml                0.17.21
ruamel.yaml.clib           0.2.6
scikit-image               0.19.3
scikit-learn               1.1.1
scipy                      1.9.1
selenium                   4.4.3
setuptools                 58.1.0
setuptools-scm             7.0.5
sgmllib3k                  1.0.0
shellingham                1.5.0
six                        1.16.0
slate                      0.5.2
smart-open                 6.2.0
smmap                      5.0.0
sniffio                    1.3.0
socketio                   0.2.1
sortedcontainers           2.4.0
SoundFile                  0.10.3.post1
soupsieve                  2.3.2.post1
SQLAlchemy                 1.3.24
sqlalchemy2-stubs          0.0.2a29
starlette                  0.19.1
tb-nightly                 2.10.0a20220806
tenacity                   8.1.0
tencentcloud-sdk-python    3.0.723
tensorboard-data-server    0.6.1
tensorboard-plugin-wit     1.8.1
terminal                   0.4.0
text-unidecode             1.3
thefuzz                    0.19.0
threadpoolctl              3.1.0
tifffile                   2022.8.3
tinydb                     4.7.0
tomli                      2.0.1
tomlkit                    0.11.5
torch                      1.12.1
torchvision                0.13.1
tortoise-orm               0.19.2
tqdm                       4.64.0
trio                       0.21.0
trio-websocket             0.9.2
typing_extensions          4.4.0
tzdata                     2022.7
tzlocal                    4.2
ua-parser                  0.16.1
ujson                      5.5.0
Unidecode                  1.3.4
urllib3                    1.26.10
user-agents                2.2.0
uvicorn                    0.20.0
virtualenv                 20.16.5
watchfiles                 0.18.1
watchgod                   0.8.2
wcwidth                    0.2.5
webencodings               0.5.1
webrtcvad                  2.0.10
websockets                 10.4
wenxin-api                 0.0.4
Werkzeug                   2.2.1
wheel                      0.37.1
win32-setctime             1.1.0
windows-curses             2.3.0
wordcloud                  1.8.2.2
wsproto                    1.2.0
yapf                       0.32.0
yarl                       1.8.1
zhconv                     1.4.3
zipfile36                  0.1.3
zipp                       3.11.0
zope.interface             5.4.0

**Comment by CMHopeSunshine** [comment]
在v0.1.4版本修复了，你更新试试

**Comment by Nenot233** [comment]
已解决，似乎是未完全关闭程序再开启程序导致数据库无法完全关闭，新程序无法读取程序
