### ISSUE TITLE
启动报错 AttributeError: type object 'Item' has no attribute 'ListBodyField'

### ISSUE THREAD

**Issue by adios-amigos** [CMHopeSunshine/nonebot-plugin-learning-chat#40]
06-25 16:27:00 [ERROR] nonebot | Failed to import "nonebot_plugin_learning_chat"
Traceback (most recent call last):
  File "G:\robot\bot\Murasame\bot.py", line 14, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "G:\robot\bot\Murasame\.venv\lib\site-packages\nonebot\plugin\load.py", line 125, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "G:\robot\bot\Murasame\.venv\lib\site-packages\nonebot\plugin\load.py", line 62, in load_all_plugins
    return manager.load_all_plugins()
  File "G:\robot\bot\Murasame\.venv\lib\site-packages\nonebot\plugin\manager.py", line 175, in load_all_plugins
    return set(
  File "G:\robot\bot\Murasame\.venv\lib\site-packages\nonebot\plugin\manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "G:\robot\bot\Murasame\.venv\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "G:\robot\bot\Murasame\.venv\lib\site-packages\nonebot\plugin\manager.py", line 241, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\robot\bot\Murasame\.venv\lib\site-packages\nonebot_plugin_learning_chat\__init__.py", line 14, in <module>
    from . import web_api, web_page
  File "G:\robot\bot\Murasame\.venv\lib\site-packages\nonebot_plugin_learning_chat\web_api.py", line 19, in <module>
    from .web_page import login_page, admin_app
  File "G:\robot\bot\Murasame\.venv\lib\site-packages\nonebot_plugin_learning_chat\web_page.py", line 493, in <module>
    listItem=AmisList.Item(body=[AmisList.Item.ListBodyField(name="msg")]),
AttributeError: type object 'Item' has no attribute 'ListBodyField'
上个版本使用正常，更新后出现此报错，请问如何解决。

**Comment by CMHopeSunshine** [comment]
更新到最新版

**Comment by adios-amigos** [comment]
已升级到0.2.3版本，仍出现此错误

**Comment by CMHopeSunshine** [comment]
那就升级一下amis-python的版本
`pip install amis-python -U`

**Comment by adios-amigos** [comment]
升级完amis-python能够正常运行了，谢谢大佬
