### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by SkinnyLi** [CMHopeSunshine/nonebot-plugin-learning-chat#5]
Traceback (most recent call last):
  File "C:\Yunzai\Yunzai-Bot\plugins\py-plugin\main.py", line 13, in <module>
    nonebot.run(root)
  File "C:\Yunzai\Yunzai-Bot\plugins\py-plugin\nonebot\__init__.py", line 56, in run
    _driver.run([str(x) for x in _driver.config.plugins])
  File "C:\Yunzai\Yunzai-Bot\plugins\py-plugin\nonebot\drivers.py", line 48, in run
    loop.run_until_complete(self.serve(plugins))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1899, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Yunzai\Yunzai-Bot\plugins\py-plugin\nonebot\drivers.py", line 62, in serve
    load_plugin(plugin.replace("-", "_"))
  File "C:\Yunzai\Yunzai-Bot\plugins\py-plugin\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Yunzai\Yunzai-Bot\plugins\py-plugin\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Yunzai\Yunzai-Bot\plugins\py-plugin\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\py-plugin-gjPTkcIP-py3.10\lib\site-packages\nonebot_plugin_learning_chat\__init__.py", line 14, in <module>
    from . import web_api, web_page
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\py-plugin-gjPTkcIP-py3.10\lib\site-packages\nonebot_plugin_learning_chat\web_api.py", line 8, in <module>
    from nonebot import get_bot, get_app
ImportError: cannot import name 'get_app' from 'nonebot' (C:\Yunzai\Yunzai-Bot\plugins\py-plugin\nonebot\__init__.py)

**Comment by CMHopeSunshine** [comment]
py-plugin的问题，请让py-plugin的作者适配
