### ISSUE TITLE
导入 `ColumnList` 时出错

### ISSUE THREAD

**Issue by mute23-code** [CMHopeSunshine/nonebot-plugin-learning-chat#7]
报错如下：
```
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\linxi-doM17b9W-py3.10\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\linxi-doM17b9W-py3.10\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\linxi-doM17b9W-py3.10\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\linxi-doM17b9W-py3.10\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\linxi-doM17b9W-py3.10\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\linxi-doM17b9W-py3.10\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\linxi-doM17b9W-py3.10\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\linxi-doM17b9W-py3.10\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\linxi_bot\.\bot.py", line 28, in <module>
    nonebot.load_plugins('plugins')
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\linxi-doM17b9W-py3.10\lib\site-packages\nonebot\plugin\load.py", line 45, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\linxi-doM17b9W-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
    return set(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\linxi-doM17b9W-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\linxi-doM17b9W-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\linxi-doM17b9W-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\linxi_bot\.\plugins\learning_chat\__init__.py", line 14, in <module>
    from . import web_api, web_page
  File "C:\linxi_bot\.\plugins\learning_chat\web_api.py", line 19, in <module>
    from .web_page import login_page, admin_app
  File "C:\linxi_bot\.\plugins\learning_chat\web_page.py", line 1, in <module>
    from amis import ColumnList, AmisList, ActionType, TableCRUD, TableColumn
ImportError: cannot import name 'ColumnList' from 'amis' (C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\linxi-doM17b9W-py3.10\lib\site-packages\amis\__init__.py)
```

`pip list` 查看，发现有amis，且版本号为`0.1.1`
```
amis                       0.1.1
```

**Comment by CMHopeSunshine** [comment]
库名不叫amis
```
pip uninstall amis
pip install amis-python
```

**Comment by mute23-code** [comment]
原来如此，谢谢大佬
